version: '3.3'

services:
    supervisord:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: supervisord
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: supervisord
        container_name: supervisord
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
        hostname: supervisord
        image: ${DOCKER_REGISTRY:-}${OS:-}supervisord:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 9001:9001
#        restart: unless-stopped
        secrets:
            - supervisord.pwd
        volumes:
            - ./vols/log:/var/log

secrets:
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
