version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on 
# containerOS: alpine

services:
    supervisord:
# build arguments, only needed for building
        build:        
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: supervisord
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.12.0}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: supervisord
                version.cbf: $CBF_VERSION
# common arguments, for building and deploy
        container_name: supervisord
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
        hostname: supervisord
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${CONTAINER_TAG:-latest}
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - 9001:9001
#        restart: unless-stopped
        secrets:                              # references to 'secrets' section below 
            - supervisord.pwd
        volumes:
            - ./vols/log:/var/log             # do not save aplication logs inside container 

# secrets only needed for deploy
secrets:                                      # location of secrets files in host filesystem 
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
