version: '3.3'

services:
    supervisord:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION}"
                CONTAINER_NAME: supervisord
                CONTAINER_VERSION: 3.0.0
                FROM_BASE: base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.7
                - base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: supervisord
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: ${CFG_PASS}
            SUPERVISORD_USER: ${CFG_USER}
        hostname: supervisord
        image: supervisord:20180322
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 9001:9001
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
