version: '3.3'

services:
    supervisord:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: supervisord
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: supervisord
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
        hostname: supervisord
        image: ${DOCKER_REGISTRY:-}supervisord:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 9001:9001
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
