version: '3.2'

services:
    supervisord:
        build:
            args:
                CONTAINER_NAME: supervisord
                CONTAINER_VERSION: 1.0.8
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180329
            cache_from:
                - alpine:3.6
                - base_container:20180329
            context: .
            dockerfile: Dockerfile
        container_name: supervisord
        environment:
            SUPERVISORD_PASS: ${CFG_PASS}
            SUPERVISORD_USER: ${CFG_USER}
        hostname: supervisord
        image: supervisord:20180322
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 9001:9001
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
